image: alexbirne/texlive2018

thesis:
  stage: build
  script:
    - cd DecayRates && make
    - cd HFLAV_Bd2Dpi && make
  cache:
    untracked: true
  artifacts:
    paths:
      - DecayRates/DecRates.pdf
      - HFLAV_Bd2Dpi/HFLAV.pdf
  only:
    - master
